# Generated by Django 4.1 on 2022-08-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128)),
                ('language', models.CharField(choices=[('RU', 'Русский'), ('ENG', 'English')], max_length=3)),
                ('part_of_speech', models.CharField(blank=True, choices=[('N', 'Существительное | Noun'), ('ADJ', 'Прилагательное | Adjective'), ('NUM', 'Числительное | Numeral'), ('PRN', 'Местоимение | Pronoun'), ('V', 'Глагол | Verb'), ('ADV', 'Наречие | Adverb'), ('PRT', 'Причастие | Participle'), ('PRE', 'Предикатив'), ('DEP', 'Деепричастие'), ('PT', 'Предлог | Pretext'), ('U', 'Союз | Union'), ('I', 'Междометие | Interjection'), ('CH', 'Частица'), ('MOD', 'Модальные слова')], max_length=3)),
                ('image', models.FileField(blank=True, upload_to='images/')),
            ],
        ),
    ]
