# Generated by Django 4.1 on 2022-08-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEW_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='image',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='word',
            name='image_verified_by_administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='voice_file',
            field=models.FileField(blank=True, upload_to='voices/'),
        ),
        migrations.AddField(
            model_name='word',
            name='word_verified_by_administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, choices=[('N', 'Существительное | Noun'), ('ADJ', 'Прилагательное | Adjective'), ('NUM', 'Числительное | Numeral'), ('PRN', 'Местоимение | Pronoun'), ('V', 'Глагол | Verb'), ('ADV', 'Наречие | Adverb'), ('PRT', 'Причастие | Participle'), ('PT', 'Предлог | Pretext'), ('U', 'Союз | Union'), ('I', 'Междометие | Interjection'), ('PRE', 'Предикатив'), ('DEP', 'Деепричастие'), ('CH', 'Частица'), ('MOD', 'Модальные слова')], max_length=3),
        ),
    ]
