# Generated by Django 4.1 on 2022-08-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEW_app', '0003_alter_word_options_alter_word_part_of_speech_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translates',
            field=models.ManyToManyField(to='LEW_app.word'),
        ),
        migrations.DeleteModel(
            name='Translate',
        ),
    ]
